# Generated by Django 3.0.5 on 2020-05-06 08:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('good', 'Good'), ('evil', 'Evil')], max_length=32)),
                ('name', models.CharField(choices=[('loyal1', 'Loyal1'), ('loyal2', 'Loyal2'), ('loyal3', 'Loyal3'), ('loyal4', 'Loyal4'), ('loyal5', 'Loyal5'), ('percival', 'Percival'), ('merlin', 'Merlin'), ('minion1', 'Minion1'), ('minion2', 'Minion2'), ('minion3', 'Minion13'), ('mordred', 'Mordred'), ('assassin', 'Assassin'), ('morgana', 'Morgana'), ('oberon', 'Oberon')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('number_of_players', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(5)])),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(to='games.Role')),
            ],
        ),
    ]
