# Generated by Django 3.0.5 on 2020-04-17 12:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('Good', 'good'), ('Evil', 'evil')], max_length=32)),
                ('name', models.CharField(choices=[('Loyal Servant of Arthur', 'loyal1'), ('Loyal Servant of Arthur', 'loyal2'), ('Loyal Servant of Arthur', 'loyal3'), ('Loyal Servant of Arthur', 'loyal4'), ('Loyal Servant of Arthur', 'loyal5'), ('Percival', 'percival'), ('Merlin', 'merlin'), ('Minion of Mordred', 'minion1'), ('Minion of Mordred', 'minion2'), ('Minion of Mordred', 'minion3'), ('Mordred', 'mordred'), ('Assassin', 'assassin'), ('Morgana', 'morgana'), ('Oberon', 'oberon')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('number_of_players', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(5)])),
                ('players_joined', models.PositiveIntegerField(default=0)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(to='games.Role')),
            ],
        ),
    ]
