# Generated by Django 3.0.5 on 2020-04-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200417_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players_joined',
        ),
    ]
