# Generated by Django 3.0.5 on 2020-05-06 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('player_num', models.PositiveIntegerField()),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', related_query_name='players', to='games.Game')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', related_query_name='player', to='games.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', related_query_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
