# Generated by Django 3.0.5 on 2020-04-29 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_players_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0003_auto_20200429_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_related', related_query_name='players', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_related', related_query_name='players', to='games.Role'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_related', related_query_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
