export const CHOOSE_ROLE = 'CHOOSE_ROLE';
export const REMOVE_ROLE = 'REMOVE_ROLE';
export const INCREASE_NUMBER_OF_PLAYERS = 'INCREASE_NUMBER_OF_PLAYERS';
export const DECREASE_NUMBER_OF_PLAYERS = 'DECREASE_NUMBER_OF_PLAYERS';

export const START_GAME = 'START_GAME';

export const WS_CONNECT = 'WS_CONNECT';
export const WS_DISCONNECT = 'WS_DISCONNECT';
export const WS_CONNECTED = 'WS_CONNECTED';
export const WS_DISCONNECTED = 'WS_DISCONNECTED';
