export const CHOOSE_AVATAR = 'CHOOSE_AVATAR';

export const CHOOSE_ROLE = 'CHOOSE_ROLE';
export const REMOVE_ROLE = 'REMOVE_ROLE';
export const SET_NUMBER_OF_PLAYERS = 'SET_NUMBER_OF_PLAYERS';

export const SET_PLAYER_TOKEN = 'SET_PLAYER_TOKEN';
export const SET_GAME_QUESTS = 'SET_GAME_QUESTS';
export const START_GAME = 'START_GAME';
export const UPDATE_GAME = 'UPDATE_GAME';
export const SET_QUEST_CHOSEN_PLAYERS = 'SET_QUEST_CHOSEN_PLAYERS';
export const SET_QUEST_VOTED_PLAYERS = 'SET_QUEST_VOTED_PLAYERS';
export const SET_QUEST_VOTE_RESULT = 'SET_QUEST_VOTE_RESULT';
export const SET_QUEST_RESULT = 'SET_QUEST_RESULT';
export const SET_ASSASSINATION_STATE = 'SET_ASSASSINATION_STATE';
export const SET_ASSASSINATION_RESULT = 'SET_ASSASSINATION_RESULT';
export const SET_END_GAME = 'SET_END_GAME';
export const SET_PLAYER_LEFT = 'SET_PLAYER_LEFT';
export const SET_PLAYER_DISCONNECTED = 'SET_PLAYER_DISCONNECTED';

export const WS_CONNECT = 'WS_CONNECT';
export const WS_DISCONNECT = 'WS_DISCONNECT';
export const WS_CONNECTED = 'WS_CONNECTED';
export const WS_DISCONNECTED = 'WS_DISCONNECTED';
export const WS_SEND = 'WS_SEND';
