export const CHOOSE_ROLE = 'CHOOSE_ROLE';
export const REMOVE_ROLE = 'REMOVE_ROLE';
export const INCREASE_NUMBER_OF_PLAYERS = 'INCREASE_NUMBER_OF_PLAYERS';
export const DECREASE_NUMBER_OF_PLAYERS = 'DECREASE_NUMBER_OF_PLAYERS';
