# Generated by Django 3.0.5 on 2020-06-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
